- type: job
  parent: CMJobBase
  id: SCPSecurityRecruit
  name: scp-job-name-security-recruit
  description: scp-job-description-security-recruit
  playTimeTracker: SCPSecurityRecruit
  weight: 5
  startingGear: SCPGearSecurityRecruit
  icon: "CMJobIconMilitaryPolice"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-cmp
  accessGroups:
  - MP
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: mp
  minimapBackground:
   sprite: _RMC14/Interface/map_blips.rsi
   state: background_mp
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillEndurance: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: "SR"

- type: entity
  parent: CMSpawnPointJobBase
  id: SCPSpawnPointSecurityRecruit
  name: security recruit spawn point
  components:
  - type: SpawnPoint
    job_id: CMMilitaryPolice
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: military_police

- type: playTimeTracker
  id: SCPSecurityRecruit
  isHumanoid: true
